Repository isofit/isofit, pull requests merged in 2024-03, with the labels that each got.

#449 CI workflow fixes
  isofit/utils/template_construction.py
Labels: bugfix

#450 Updated release workflow
  .github/workflows/release.yml
Labels: bugfix

#461 Ray Out of Memory
  isofit/__init__.py
  isofit/core/isofit.py
  isofit/radiative_transfer/radiative_transfer_engine.py
  isofit/utils/analytical_line.py
  isofit/utils/apply_oe.py
  isofit/utils/atm_interpolation.py
  isofit/utils/empirical_line.py
  isofit/utils/ewt_from_reflectance.py
  isofit/utils/extractions.py
  isofit/utils/segment.py
Labels: bugfix

#469 `isofit.root` replacement
  isofit/__main__.py
  isofit/core/env.py
  isofit/test/test_env.py
  isofit/utils/downloads.py
Labels: bugfix, enhancement

#468 Final workflow fixes.
  .github/workflows/test-pythonpath-ubuntu.yml
  docs/source/conf.py
  docs/source/custom/installation.rst
  isofit/__init__.py
  isofit/core/geometry.py
  isofit/radiative_transfer/six_s.py
  isofit/test/test_cli.py
  isofit/utils/empirical_line.py
  recipe/environment_isofit_basic.yml
  scripts/download-and-unpack-sRTMnet.sh
  scripts/run-tests.sh
  setup.cfg
Labels: bugfix

#476 Add wavelength checks.
  isofit/core/forward.py
  isofit/utils/apply_oe.py
Labels: enhancement
