Repository isofit/isofit, pull requests merged in 2024-02, with the labels that each got.

#438 EnMAP support in apply_oe - patch.
  isofit/utils/apply_oe.py
Labels: bugfix

#408 New physics-based sun+sky glint model for water surfaces.
  examples/20151026_SantaMonica/configs/prm20151026t173213_D8W_6s.json
  examples/20151026_SantaMonica/configs/prm20151026t173213_D8p5W_6s.json
  examples/20151026_SantaMonica/configs/prm20151026t173213_D9p5W_6s.json
  examples/20171108_Pasadena/lut_multi/LUT_AOT550-0.0100_H2OSTR-1.5000.json
  examples/20171108_Pasadena/lut_multi/LUT_AOT550-0.0100_H2OSTR-2.0000.json
  examples/20171108_Pasadena/lut_multi/LUT_AOT550-0.1000_H2OSTR-1.5000.json
  examples/20171108_Pasadena/lut_multi/LUT_AOT550-0.1000_H2OSTR-2.0000.json
  examples/20190806_ThermalIR/configs/joint_isofit_with_prof_WATER_nogrid.json
  isofit/configs/sections/radiative_transfer_config.py
  isofit/core/forward.py
  isofit/inversion/inverse_simple.py
  isofit/radiative_transfer/radiative_transfer.py
  isofit/surface/__init__.py
  isofit/surface/surface_additive_glint.py
  isofit/surface/surface_glint_model.py
  isofit/test/test_cli.py
  isofit/utils/analytical_line.py
  isofit/utils/apply_oe.py
  isofit/utils/atm_interpolation.py
  multisurface_oe_template.json
Labels: enhancement

#383 Lut
  .github/workflows/example-testing.yml
  .github/workflows/py-hypertrace.yml
  .github/workflows/utils-workflow.yml
  README.rst
  examples/20151026_SantaMonica/configs/prm20151026t173213_D8W_6s.json
  examples/20151026_SantaMonica/configs/prm20151026t173213_D8p5W_6s.json
  examples/20151026_SantaMonica/configs/prm20151026t173213_D9W_6s.json
  examples/20151026_SantaMonica/configs/prm20151026t173213_D9p5W_6s.json
  examples/20171108_Pasadena/configs/ang20171108t173546_darklot.json
  examples/20171108_Pasadena/configs/ang20171108t173546_horse.json
  examples/20171108_Pasadena/configs/ang20171108t184227_astrogreen.json
  examples/20171108_Pasadena/configs/ang20171108t184227_astrored.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-libradtran.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-multimodtran-topoflux.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-multimodtran.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-oversmoothed.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn-undersmoothed.json
  examples/20171108_Pasadena/configs/ang20171108t184227_beckmanlawn.json
  examples/20171108_Pasadena/configs/ang20171108t184227_libradtran.inp
  examples/20171108_Pasadena/configs/ang20171108t184227_modtran.json
  examples/20171108_Pasadena/configs/ang20171108t184227_multimodtran.json
  examples/20171108_Pasadena/configs/ang20171108t184227_surface.json
  examples/20171108_Pasadena/run_example_libradtran.py
  examples/20171108_Pasadena/run_example_libradtran.sh
  examples/20171108_Pasadena/run_example_modtran.py
  examples/20171108_Pasadena/run_topoflux_example.py
  examples/py-hypertrace/hypertrace.py
  isofit/__init__.py
  isofit/configs/sections/radiative_transfer_config.py
  isofit/core/common.py
  isofit/core/fileio.py
  isofit/core/forward.py
  isofit/core/geometry.py
  isofit/core/instrument.py
  isofit/core/isofit.py
  isofit/inversion/inverse_simple.py
  isofit/radiative_transfer/libradtran.py
  isofit/radiative_transfer/look_up_tables.py
  isofit/radiative_transfer/luts.py
  isofit/radiative_transfer/modtran.py
  isofit/radiative_transfer/radiative_transfer.py
  isofit/radiative_transfer/radiative_transfer_engine.py
  isofit/radiative_transfer/sRTMnet.py
  isofit/radiative_transfer/six_s.py
  isofit/surface/surface_additive_glint.py
  isofit/test/disabled.test_lut.py
  isofit/test/test_cli.py
  isofit/test/test_geometry.py
  isofit/test/test_libradtran.py
  isofit/utils/6S_to_sRTMnet.py
  isofit/utils/analytical_line.py
  isofit/utils/apply_oe.py
  isofit/utils/atm_interpolation.py
  isofit/utils/empirical_line.py
  isofit/utils/extractions.py
  isofit/utils/multisurface_oe.py
  isofit/utils/segment.py
  isofit/utils/template_construction.py
  recipe/environment_isofit_basic.yml
  setup.cfg
Labels: enhancement

#448 CLI for downloading extras
  isofit/utils/downloads.py
  recipe/environment_isofit_basic.yml
  setup.cfg
Labels: bugfix, enhancement

#453 Downloads CLI updates
  docs/source/custom/installation.rst
  isofit/__init__.py
  isofit/utils/downloads.py
  recipe/environment_isofit_basic.yml
  setup.cfg
Labels: enhancement

#455 Utility click
  isofit/__main__.py
  isofit/test/test_cli_machinery.py
  isofit/utils/analytical_line.py
  isofit/utils/apply_oe.py
  isofit/utils/empirical_line.py
  isofit/utils/ewt_from_reflectance.py
  isofit/utils/surface_model.py
Labels: enhancement, cleanup
