Repository isofit/isofit, pull requests merged in 2024-12, with the labels that each got.

#604 Added Logger definition to radiative_transfer.py
  isofit/radiative_transfer/radiative_transfer.py
Labels: bugfix

#608 Changes to get configure_and_exit flag to work
  isofit/radiative_transfer/engines/modtran.py
Labels: cleanup

#581 ApplyOE Doc Updates
  isofit/utils/apply_oe.py
  isofit/utils/template_construction.py
Labels: enhancement, cleanup

#616 Pathlib fix to examples bug
  isofit/configs/sections/radiative_transfer_config.py
  isofit/radiative_transfer/radiative_transfer_engine.py
Labels: bugfix
