Repository isofit/isofit, pull requests merged in 2025-01, with the labels that each got.

#612 Add function to do radiance <-> transmittance conversion.
  isofit/inversion/inverse_simple.py
  isofit/radiative_transfer/radiative_transfer.py
Labels: enhancement

#611 RTM bug fixes
  isofit/core/common.py
  isofit/core/instrument.py
  isofit/radiative_transfer/engines/modtran.py
  isofit/radiative_transfer/engines/six_s.py
  isofit/radiative_transfer/luts.py
Labels: bugfix

#618 Fix workflows cache rate limiting
  .github/workflows/test-pip-package-ubuntu.yml
  .github/workflows/test-pythonpath-ubuntu.yml
Labels: bugfix

#623 Patch to RT conversion functions.
  isofit/inversion/inverse_simple.py
  isofit/radiative_transfer/radiative_transfer.py
Labels: bugfix

#613 Extra Downloads Updating Feature
  .github/workflows/test-pip-package-ubuntu.yml
  .github/workflows/test-pythonpath-ubuntu.yml
  isofit/__init__.py
  isofit/__main__.py
  isofit/data/__init__.py
  isofit/data/cli/__init__.py
  isofit/data/cli/data.py
  isofit/data/cli/examples.py
  isofit/data/cli/image_cube.py
  isofit/data/cli/modtran.py
  isofit/data/cli/sixs.py
  isofit/data/cli/srtmnet.py
  isofit/data/download.py
  isofit/data/ini.py
  isofit/test/test_cli.py
  isofit/test/test_cli_machinery.py
  isofit/test/test_env.py
Labels: enhancement, question

#626 Cache Updating & Data CLI Changes
  .github/workflows/prebuild.yml
  .github/workflows/test_path.yml
  .github/workflows/test_pip.yml
  isofit/__main__.py
  isofit/data/build_examples.py
  isofit/data/cli/__init__.py
  isofit/data/cli/data.py
  isofit/data/cli/examples.py
  isofit/data/cli/image_cube.py
  isofit/data/cli/modtran.py
  isofit/data/cli/sixs.py
  isofit/data/cli/srtmnet.py
  isofit/data/download.py
  isofit/data/ini.py
  isofit/test/test_cli_machinery.py
Labels: bugfix

#627 RTE Configuration Errors
  isofit/configs/sections/radiative_transfer_config.py
  isofit/radiative_transfer/radiative_transfer_engine.py
Labels: bugfix
