Repository isofit/isofit, pull requests merged in 2025-05, with the labels that each got.

#682 CLI Docs Update
  docs/source/custom/data.rst
  docs/source/custom/installation.rst
  isofit/radiative_transfer/engines/six_s.py
Labels: bugfix, cleanup

#650 Config Templating
  isofit/__main__.py
  isofit/core/isofit.py
  isofit/data/__init__.py
  isofit/data/download.py
  isofit/data/ini.py
  isofit/utils/template_construction.py
Labels: enhancement

#688 Fix IndexError due to missing key 'observer_zenith' in prebuilt LUT.
  isofit/utils/template_construction.py
Labels: bugfix
